### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by zulu14** [potato1992/Iphone_usb_tethering_fix#1] opened 2021-02-06 15:50 UTC
HELLO,
thank you for this wonderful repo
we have to try to make a new driver for openwrt

but i get this error: (i have manualy change to /tmp, openwrt d'ont have a build folder in the modules repo)

[INFO] Kernel version , using the patch 5.3.0

make -C /tmp M=/root modules
make[1]: Entering directory '/tmp'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/tmp'
make: *** [Makefile:6: default] Error 2

**Comment by potato1992** [comment] 2021-02-06 16:54
> HELLO,
> thank you for this wonderful repo
> we have to try to make a new driver for openwrt
> 
> but i get this error: (i have manualy change to /tmp, openwrt d'ont have a build folder in the modules repo)
> 
> [INFO] Kernel version , using the patch 5.3.0
> 
> make -C /tmp M=/root modules
> make[1]: Entering directory '/tmp'
> make[1]: *** No rule to make target 'modules'. Stop.
> make[1]: Leaving directory '/tmp'
> make: *** [Makefile:6: default] Error 2

Since a openwrt device does not have the full tool-chain to build the driver, you can't build this drive on your op device.  Please build your openwrt firmware on a PC. There is a official guide on how to build openwrt on their [website](https://openwrt.org/docs/guide-developer/quickstart-build-images).

After you get the source that of the same version of your openwrt, find and modify the /ipheth.c inside drivers/net/usb/ and modify it as instructed in the Readme.md of this project. Then build the firmware, it doesn't matter if you are not satisfied with the official op version, all you need is just the driver (ipheth.ko file). Then I think the new ko file will work for your openwrt.

Also, there is a trick fix published by [wnienhaus](https://github.com/libimobiledevice/libimobiledevice/issues/1038#issuecomment-735213839), you can try it if you do not want to build the openwrt firmware.

**Comment by kva** [comment] 2021-02-06 19:02
nice repo, @potato1992 
In linux, I always run `chmod +x make.sh`, file name without dot-slash (./) before it. But I tried `chmod +x ./make.sh`, it happens to work too.

Unfortunately, I need superuser's privilege to execute `make.sh` file, it gave errors if executed without `sudo`. Maybe you should try `sudo ./make.sh` @zulu14

**Comment by potato1992** [comment] 2021-02-06 22:20
> nice repo, @potato1992
> In linux, I always run `chmod +x make.sh`, file name without dot-slash (./) before it. But I tried `chmod +x ./make.sh`, it happens to work too.
> 
> Unfortunately, I need superuser's privilege to execute `make.sh` file, it gave errors if executed without `sudo`. Maybe you should try `sudo ./make.sh` @zulu14

Iin openwrt there is no "normal user", it's root user in default. The problem should be the fact that the openwrt does not include the neccessary build library or even the header files with it (a router have limited drive space).

**Comment by zulu14** [comment] 2021-02-06 22:32
we has just get the ipheth file, and i have DL you new commit, i get this:
![image](https://user-images.githubusercontent.com/71033768/107131053-a9238e80-68d3-11eb-900b-ac1c5dd47e56.png)

**Comment by zulu14** [comment] 2021-02-06 22:48
on debian after openwrt we have the same first issues
![image](https://user-images.githubusercontent.com/71033768/107131362-d5d8a580-68d5-11eb-990a-01fc3c0c5d51.png)

**Comment by potato1992** [comment] 2021-02-06 22:51
> we has just get the ipheth file, and i have DL you new commit, i get this:
> 
> ![image](https://user-images.githubusercontent.com/71033768/107131053-a9238e80-68d3-11eb-900b-ac1c5dd47e56.png)
> 
> 

Can you type in the command line and see if let command is supported?

And also, although the script has .sh suffix, it's based on bash.

**Comment by zulu14** [comment] 2021-02-06 22:53
oh with bash is so great :)
![image](https://user-images.githubusercontent.com/71033768/107131427-775ff700-68d6-11eb-85a9-5ec5c2fa23c4.png)

**Comment by zulu14** [comment] 2021-02-06 22:54
its fail again :/
![image](https://user-images.githubusercontent.com/71033768/107131457-afffd080-68d6-11eb-9938-d68af76e5e35.png)

**Comment by potato1992** [comment] 2021-02-06 23:09
> its fail again :/
> ![image](https://user-images.githubusercontent.com/71033768/107131457-afffd080-68d6-11eb-9938-d68af76e5e35.png)

What is the output of ls -l /lib/modules/$(uname -r)/build on your debian PC?

**Comment by zulu14** [comment] 2021-02-06 23:10
empty

**Comment by potato1992** [comment] 2021-02-06 23:34
> empty

The /lib/modules/$(uname -r)/build should be a soft link of the linux header folder of the same version as uname -r, for example, in my case:

lrwxrwxrwx 1 root root 39 Jan 19 01:34 /lib/modules/5.4.0-65-generic/build -> /usr/src/linux-headers-5.4.0-65-generic

Thus this should not be a issue of the repository. I cannot include every version of Linux kernel in the repository, thus the compilation will totally rely on the Linux header files locally.  Try install the linux header and construct the proper soft link. see if the [example](https://raspberrypi.stackexchange.com/questions/5230/getting-no-rule-to-make-target-modules-stop-error-when-running-makefile-w) would help.

Since I cannot reproduce the same issue of yours, thus limited help can be offered.  I have checked the raspbarry pi os (debian based) and it runs smoothly, some distributors just have removed the files that required for kernel module built for the purpose of minimizing the image size.

I would suggest that if you cannot get it work in the end, install a official version of ubuntu/debian in a vmware machine, then install and switch to the linux kernel 5.4.34-1, the compilation should work on it and just copy the generated **ipheth.ko** file to the PVE PC, finally perform a manual installation as instructed in the Readme.md.

**Comment by potato1992** [comment] 2021-02-21 22:41
> empty

Hello, have you solve your problem? I was just building my own Openwrt Image for my Nanopi R2S (Code from the latest Lean version), and  found that the Iphone tethering problem has already been solved, in my case, the following code:
```
lede/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.4.95/drivers/net/usb/ipheth.c
lede/build_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/linux-5.4.95/drivers/net/usb/ipheth.c
```
they have already been fixed for the buffer size issue, so if you happen not to know how to build your own openwrt module, the easist way is just to upgrade your firmware to the latest image (maybe the latest snapshots if you are using the official image).  I will close the issue as the latest official openwrt code has already been fixed for this problem.

**Closed as completed by potato1992** 2021-02-21 22:41 UTC
